### ISSUE TITLE
Custom connectors

### ISSUE THREAD

**Issue by pakokrew** [EthWorks/useDApp#100]
Amazing tools you guys are creating here!

Obviously, using InjectedProvider is not always the unique option dApps need. Supporting other connectors such as WalletConnect is a must-have. 

Could be great to add support of common connectors available on web3-react with easy setup from the useDApp configuration object, like in web3modal.

**Comment by marekkirejczyk** [comment]
We are supporting them, you can use `activate`, that is returned by `useEthers` hook.

Works exactly like web3-react (it is in fact web3-react function)

See docs:
https://usedapp.readthedocs.io/en/latest/core.html#useethers

**Comment by pakokrew** [comment]
My bad

**Comment by marekkirejczyk** [comment]
@pakokrew No worries, the documentation is lacking Guide for that :) 
Perhaps you would like to write it :D

**Comment by pakokrew** [comment]
Would love to help, will certainly do after I've done extensive use of the lib.

As a first-time user, I wonder why you export this `useEther` hook, which is basically the same as `useWeb3React`, with just this helper for injected connecter. This is confusing from a developer side, I think directly exporting useWeb3React would directly tell devs to check the web3-react doc at source. And maybe export this default injected provider/activateBrowerWallet somewhere else.

**Comment by marekkirejczyk** [comment]
There are a few reasons to overwrite useWeb3React:
- we don't assume everyone knows Web3-React 
- we want to have `activateBrowserWallet` working out-of-the-box
- in the future we might want to add/remove more functionality, break compatibility etc

I think it is a good idea to add info in documentation about web3-react (I see you did, already merged).
