### ISSUE TITLE
Error after update to 0.3.0

### ISSUE THREAD

**Issue by kacperkurek** [EthWorks/useDApp#119]
After update app throws this error 
`Module not found: Can't resolve '@ethersproject/abi' in '/Users/kacper/Projects/earnbase/node_modules/@usedapp/core/dist/src/constants/abi'`

**Comment by nezouse** [comment]
Hi, the last change to this dependency was made 2 months ago. Could you provide some more details, a reproduction or maybe a link to the repo if it's open sourced?

And maybe just try to remove node_modules and install it again.

**Comment by gasolin** [comment]
also got `Can't resolve 'ethers' in 'node_modules/@usedapp/core/dist/src/helpers'` after did `npm install -S @ethersproject/abi` in project

**Comment by kacperkurek** [comment]
Removed node_modules and install it again does not help

**Comment by marekkirejczyk** [comment]
There was mixup in dependencies, should be solved with 0.3.2
