### ISSUE TITLE
useContractFunction throws 'TypeError: Unsupported chain' when using chain id 1337

### ISSUE THREAD

**Issue by dylankilkenny** [EthWorks/useDApp#121]
when using a local ganache node with chain id 1337 the useContractFunction hook throws `TypeError: Unsupported chain`

issue seems to be coming from the call to isChainId() in providers/transactions/reducer.ts, chain id 1337 is missing from the ChainId enum.

**Comment by marekkirejczyk** [comment]
Are you trying to connect Ganache? If so we could add Ganache as supported network.

We want to add support for arbitrary network, but it is further down the road.

**Comment by marekkirejczyk** [comment]
Thank you for PR ❤️
Merged and publish in 0.3.3
