### ISSUE TITLE
Error thrown on NextJS

### ISSUE THREAD

**Issue by bitfede** [EthWorks/useDApp#131]
Hello, I was trying useDapp with NextJS earlier today and as soon as I pasted all the basic example code I got this error:

<img width="1240" alt="Screen Shot 2021-04-04 at 12 55 08 AM" src="https://user-images.githubusercontent.com/15684622/113499031-74e9da00-94e0-11eb-813b-66d5148e0218.png">

```
Server Error
ReferenceError: window is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
getItem
file:///Users/fede/Documents/learning/usedapp+nextjs/usedapp-test-web/node_modules/@usedapp/core/dist/src/hooks/useLocalStorage.js (6:16)
<unknown>
file:///Users/fede/Documents/learning/usedapp+nextjs/usedapp-test-web/node_modules/@usedapp/core/dist/src/hooks/useLocalStorage.js (29:52)
useReducer
file:///Users/fede/Documents/learning/usedapp+nextjs/usedapp-test-web/node_modules/react-dom/cjs/react-dom-server.node.development.js (1537:57)
```

This article talks about this issue with NextJS https://medium.com/frontend-digest/why-is-window-not-defined-in-nextjs-44daf7b4604e , but there are many more you can google.

Is there a way to get a fix for this so useDapp becomes NextJS compatible or it does not make sense at all for you guys? Can I help?

Thanks for your time! Have a great day!

**Comment by Sagato** [comment]
Hi Mate with the latest release this problem should be fixed. Try version 0.3.4 (latest). The latest pull request merged, checks for window object before using localStorage. greets

**Comment by marekkirejczyk** [comment]
@bitfede Can you confirm it is working with 0.3.4

**Comment by bitfede** [comment]
YES!!! It is!!! Amazing!! You guys are awesome! I had a little heart attack thought I hit a dead end, but this fix finally unblocked me. Thank you so much guys!

**Comment by bitfede** [comment]
@marekkirejczyk  Are you guys creating a slack/discord/forum community for this framework?

**Comment by coopemor** [comment]
Seems to be happening to me on the upgrade to 0.4.0 and works again if I downgrade to 0.3.24. (My first day using the project, but seems like it might be related to new version)

**Comment by AshleyRudland** [comment]
Getting the same error too:

<img width="880" alt="Screenshot 2021-06-30 at 10 29 05" src="https://user-images.githubusercontent.com/3226237/123928223-022cb580-d98e-11eb-8f79-d53876477d3b.png">

Deps as follows:

```
"@usedapp/core": "^0.4.0",
"next": "^10.0.6",
"react": "^17.0.1",
"react-dom": "^17.0.1"
```

Fantastic project, if this can be fixed that would unblock me :-)

**Comment by wminshew** [comment]
also broken for me in `0.4.0`; downgrading back to `0.3.24`
