### ISSUE TITLE
Persisting connection on page refresh

### ISSUE THREAD

**Issue by bitfede** [EthWorks/useDApp#133]
Hey Guys! It's me again, I need a quick help on this:

I want the metamask login to persist even when the page refreshes. Unfortunately with useDapp the user needs to click "connect" every time there is a change of page...

The UX of having persistent login is very important, so far I have only seen it implemented here: https://github.com/mirshko/next-web3-boilerplate
Whenever I refresh the page I am still connected with metamask and react renders a "hello 0x1A2B3..." instead of "Connect"

Is this something that can be achieved with useDapp too? Any suggestions on this topic?

Hope I'm not too annoying, I'm just looking to make the perfect login experience for my dApps. Thanks for your time :)

**Comment by bitfede** [comment]
I see somebody mentioning this topic in another repo, maybe it helps: https://github.com/MetaMask/metamask-extension/issues/7030

**Comment by dylankilkenny** [comment]
@bitfede Ive been using something like this to load the injected wallet on refresh


```TS
  const { activate } = useEthers();

  useEffect(() => {
    injected.isAuthorized().then((isAuthorized) => {
      if (isAuthorized) {
        activate(injected);
      }
    });
  }, [activate]); 
```

**Comment by bitfede** [comment]
oh wow looks like a smart solution, where is `injected` defined exactly?

**Comment by dylankilkenny** [comment]
```
import { InjectedConnector } from "@web3-react/injected-connector";

const injected = new InjectedConnector({ supportedChainIds: [1, 4, 1337] });
```

**Comment by bitfede** [comment]
Oh that's true, should have googled it, also found a similar example here https://github.com/NoahZinsmeister/web3-react/blob/v6/example/connectors.ts

Aaand just tested it! It works beautifully!!! :D

Thank you for taking the time to explain, really appreciate it. Just checked out your repos they look badass keep up the good work 💪
