### ISSUE TITLE
Missing dependencies after update to 0.3.4 or 0.3.2

### ISSUE THREAD

**Issue by kacperkurek** [EthWorks/useDApp#134]
Module not found: Can't resolve 'ethers' in '/Users/kacper/Projects/earnbase/node_modules/@usedapp/core/dist/src/helpers'
Remove node_modules does not help.

**Comment by marekkirejczyk** [comment]
Hmm, should be working with 0.3.3 onwards.
Try adding     `"ethers": "^5.1.0",` to your package.json and let us know if it helps.

**Comment by kacperkurek** [comment]
It helps thanks

**Comment by marekkirejczyk** [comment]
btw we fixed dependencies in the new version and now it should work "out-of-the-box"
