### ISSUE TITLE
Notification Types suggestion

### ISSUE THREAD

**Issue by dylankilkenny** [EthWorks/useDApp#140]
Currently all notification types are exported in a union type `Notification`. Since the properties in each type are not consistent the following code is needed to access non universal properties:

```TS
const notif = notifications[0];
if ("submittedAt" in notif && "transaction" in notif && "receipt" in notif) {
  // access all properties
}
```
Currently only `type` is accessible without a type guard. Without such type gaurd we get `Property 'submittedAt' does not exist on type 'WalletConnected'`

I think it would be cleaner to have `type` removed from the notification types and instead export the interfaces for each notification. Then we can use:

```TS
if(notif instanceof TransactionFailed){
    // access all properties
}
```

I can possibly create a PR, let me know your thoughts

**Comment by nezouse** [comment]
You don't have to check each property.
It's enough if you check if `if(notif.type === "transactionFailed")`

Types here are probably not final yet, but in this situation, I don't think that's really an issue.

**Comment by dylankilkenny** [comment]
Yes thats fair point, closing.
