### ISSUE TITLE
Persisting the connection

### ISSUE THREAD

**Issue by Sagato** [EthWorks/useDApp#145]
On Reload of the page the user always has to reconnect manually.
Is it possible to persist the connection, so that the user if he didn't explicitly remove the dapp from the connected sites
it auto connects?

greets

**Comment by marekkirejczyk** [comment]
That is a good point. 
This is related to #133.
Added to roadmap.

**Comment by kamescg** [comment]
Easy handle this via the application logic (saving automatic connections preferences in localstorage) and creating a component that automatically calls activate if a connection was previously initialized.

That being said, would be nice too also have this functionality included in the library.

**Comment by marekkirejczyk** [comment]
It is scheduled for next milestone.

**Comment by noobshow** [comment]
Is this in a version or something someone can help with?
