### ISSUE TITLE
Invalid "TypeError: Unsupported Chain" Error using useContractFunction hook

### ISSUE THREAD

**Issue by kamescg** [EthWorks/useDApp#157]
When using a hardhat node with the default chainId (31337) I am unable to send transactions using `useContractFunction` hook.

I get `TypeError: Unsupported chain` even though I've added the chainId to the config parameters used when initializing the `DappProvider` 

![image](https://user-images.githubusercontent.com/3408362/114291238-a14eaa80-9a3a-11eb-8433-530a3adc0d37.png)

![invalid-chain](https://user-images.githubusercontent.com/3408362/114291266-dd820b00-9a3a-11eb-86e6-d4266554ae51.gif)

**Comment by marekkirejczyk** [comment]
What useDApp version do you use?

**Comment by marekkirejczyk** [comment]
I looked at the code again, we don't support currently hardhat node. We could add 31337 port, that would allow sending transactions. However the multicall contract is not deployed, so calls will not work.
The feature is on the roadmap.

**Comment by kamescg** [comment]
I updated to the latest version.

Would be great to just be able to override what network's are supported. What benefit is there from hardcoding a chainId?

When testing the useDapp library I just deployed multi-call to my local network. Plus, my hardhat node might just be a fork of mainnet, which would include the multi-call smart contract.

**Comment by marekkirejczyk** [comment]
Added HardHat chainId to list of supported chains. Published in 0.3.10

**Comment by marekkirejczyk** [comment]
The benefit suppose to be type safety, but that turned out to be problematic.
Flexible chainId's are scheduled for the next milestone.

**Comment by jacobedawson** [comment]
> The benefit suppose to be type safety, but that turned out to be problematic.
> Flexible chainId's are scheduled for the next milestone.

Any updated on next milestone?

**Comment by marekkirejczyk** [comment]
We added HardHard port to the list a while ago. Is it not working for you?

**Comment by jacobedawson** [comment]
> We added HardHard port to the list a while ago. Is it not working for you?

It wasn't working for me a few days back, I've switch to Infura in the meantime, I will update here if I find Hardhat still not working.

**Comment by jacobedawson** [comment]
> We added HardHard port to the list a while ago. Is it not working for you?

So I switched back to Hardhat and I run into the follow errors (that don't appear with using Infura as the network):

1.) I receive an error "Missing multicall address for chain id 1337"
2.) When I connect to my dapp, Metamask opens and I can give permissions, but the app state (provider) does not register the change until I refresh the page

Details:

Network URL: http://127.0.0.1:8545 (issue happens also with http://localhost:8545)
Chain ID: 1337
@usedapp/core: ^0.3.17

**Comment by ironsoul0** [comment]
> > We added HardHard port to the list a while ago. Is it not working for you?
> 
> So I switched back to Hardhat and I run into the follow errors (that don't appear with using Infura as the network):
> 
> 1.) I receive an error "Missing multicall address for chain id 1337"
> 2.) When I connect to my dapp, Metamask opens and I can give permissions, but the app state (provider) does not register the change until I refresh the page
> 
> Details:
> 
> Network URL: http://127.0.0.1:8545 (issue happens also with http://localhost:8545)
> Chain ID: 1337
> @usedapp/core: ^0.3.17
> 
> In the Hardhat config, due to an issue with MetaMask (https://hardhat.org/metamask-issue.html), the chainId is set to 1337:
> 
> ```
>   networks: {
>     hardhat: {
>       chainId: 1337,
>     },
>   },
> ```
> 
> Perhaps this is the conflicting issue - I see above you reference Hardhat's default chainId of 31337, whereas the MetaMask / Hardhat issue requires the chainId to be 1337. This might be resolved if we can configure custom chainIds.

Hi there!

Did you find a way to solve this issue? I tried to change my metamask hardhat chainId to 31337 so it matches with useDApp config constants but still no luck.
