### ISSUE TITLE
Start/Build Webpack Errors on Ubuntu

### ISSUE THREAD

**Issue by stackaccount1** [EthWorks/useDApp#169]
`@usedapp/example
$ tsc --noEmit && rimraf build && webpack --mode production --progress
 | fatal: Needed a single revision
 | [webpack-cli] Failed to load '/home/user/Downloads/useDApp-master/packages/example/webpack.config.js' config
 | [webpack-cli] { Error: Command failed: git rev-parse --short HEAD
 | fatal: Needed a single revision
`
^ I am getting this error trying to use yarn &&, then yarn build on the main directory
`
[webpack-cli] Failed to load '/home/user/Downloads/useDApp-master/packages/example/webpack.config.js' config
[webpack-cli] { Error: Command failed: git rev-parse --short HEAD
fatal: Needed a single revision
`
^ this error cding into the example project and doing npm start

I am using ubuntu 20.04 , npm version 6.14.4

I spent a few hours troubleshooting NPM versions and webpack versions for a while

**Comment by nezouse** [comment]
Okay, sorry for your trouble here, it not an issue with npm or webpack.
You need to init a git repo and commit something. Webpack tries to parse your git history and it crashes if it can't be accessed.

**Comment by stackaccount1** [comment]
Thank you I needed to clone it, I appreciate it.
