### ISSUE TITLE
Better Error Handling for Calls to Contracts with invalid ABI Interface

### ISSUE THREAD

**Issue by kamescg** [EthWorks/useDApp#182]
Some of the useDapp hooks tend to abruptly fail if everything isn't perfect. As it stands I may have to pass in a contract address that may or may not have the correct ABI.

For example when using `useContractCall` hook the application often throws "Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement." if the contract doesn't have the correct ABI.

Imagine a dynamic list of contract addresses where some may be ERC20s and others not. Those list of addresses are passed into a component that attempts to call `symbol` and if the contract doesn't have a symbol function then the errors start.

Example: `const [symbolCall] = useERC20ContractCall(address, "symbol");`

![image](https://user-images.githubusercontent.com/3408362/115677496-60da1100-a305-11eb-8d95-c67eba0a0a75.png)

Which seems to be coming from `node_modules/@usedapp/core/dist/src/providers/chainState/provider.js (34:40)`

![image](https://user-images.githubusercontent.com/3408362/115677521-66cff200-a305-11eb-86f5-a208f6a5e42f.png)

What's the best way to prevent errors like this when using useDapp hooks?

**Comment by kamescg** [comment]
Just wanted to follow up on this, because this is a pretty significant pain point, because the application significantly fails ( console warnings like i.e. _React has detected a change in the order of Hooks_ and causing libraries like next.js to throw significant enough errors to display errors in the UI) if an invalid smart contract address is passed to a useContractCall hook.

Can investigate and make PR if a fix would be merged in?

**Comment by nezouse** [comment]
Sure, PRs are always welcome.

**Comment by noobshow** [comment]
I think a hook has been rendered in a loop, Conditional statement or below the top level... Just that the ordering changed on react next call/render
