### ISSUE TITLE
Website not responsive

### ISSUE THREAD

**Issue by sz-piotr** [EthWorks/useDApp#189]
![Screenshot_2021-05-02-22-23-31-721_org mozilla firefox](https://user-images.githubusercontent.com/17070569/116826660-710baf00-ab95-11eb-85e3-3cbece5f2fcd.jpg)

**Comment by noobshow** [comment]
It's responsive ability is limited to the desktop or big screen for now, I guess

**Comment by noobshow** [comment]
You plan working on it?

**Comment by sz-piotr** [comment]
Not at all. I created the issue in the hope that someone else will find time to do it ;)

**Comment by marekkirejczyk** [comment]
We will get it done, once we are done with 0xHack

**Comment by tt-marek** [comment]
Fixed!
