### ISSUE TITLE
probably missing @ethersproject/contracts export

### ISSUE THREAD

**Issue by dismedia** [EthWorks/useDApp#191]
Hi, I'm not sure, but, in order to use _useContractFunction_ hook  we need to create _Contract_ instance. That type comes from @ethersproject/contracts package.

The question is, if it should be (re)exported from useContractFunction.ts, or maybe I'm misiing something?

**Comment by nezouse** [comment]
Maybe it is some quirk of monorepo, but it works correctly in example project: https://github.com/EthWorks/useDApp/blob/master/packages/example/src/components/Notifications/Forms.tsx#L1

**Comment by dismedia** [comment]
I does, indeed. I will investigate it, but closing for now.
Thanks!
