### ISSUE TITLE
Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.

### ISSUE THREAD

**Issue by noobshow** [EthWorks/useDApp#195]
![image](https://user-images.githubusercontent.com/7571856/117860369-1f93ac00-b288-11eb-8582-6b6735d10053.png)

Couldn't figure if there's any hook call in that line, is there any?

Does this file skip a hook call?
https://github.com/EthWorks/useDApp/blob/7c5e599e5699fcaf548aa828785b364eaede23c3/packages/core/src/providers/chainState/provider.tsx#L37

The error seems to have emanated from that line

**Comment by noobshow** [comment]
Same issue still happened after I added all tokens to the useContractCalls
at a go...

I guess whenever the component rerendered it affected the hooks order in
useDapp

**Comment by noobshow** [comment]
I will try create a minimal reproduction today...

**Comment by noobshow** [comment]
Is this even production ready?
Please, I'm using this on a production dapp.

**Comment by nezouse** [comment]
Yes, we are using it for our own apps. Please provide a reproduction because I can't debug it by looking at a stack trace.

**Comment by noobshow** [comment]
Tried reproducing it with a test component that act similar to my project, couldn't get it to produce such error...

**Comment by nezouse** [comment]
Did you have this error in the example package from useDApp?

**Comment by noobshow** [comment]
I figured useContractCalls still refresh the component, even when arrays of results(in this case, BigNumber) have equal value.

Was able to figure that out with why-did-you-render...

The reason behind that is because useMemo doesn't compare object values, it only make reference comparison...

I can implement a hook that could be used to replace useMemo in the library or we could use useMemoCompare() available at useHooks

**Comment by noobshow** [comment]
Detected the line the issue came from, seems not to be the library's fault, and not even sure if its mine too but here is the hook causing the commotion amongst three components that cause this crash

```ts
import { useTokenBalance, useEthers } from "@usedapp/core";

/**
 * @todo return a key and value of [token:balance]
 */
export function useExternalBalance(address: string) {
    const {account} = useEthers();
    const etherBalance = useEtherBalance(account)
    const tokenBalance = useTokenBalance(address === '0x' ? 0 : address, account);

    return address === '0x' ? etherBalance : tokenBalance;//BUG Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement
}
```

Still can't figure out why it caused the problem, but after removing it from each components it was listed, the problem stops immediately
