### ISSUE TITLE
Work on a comparable useMemo alternative?

### ISSUE THREAD

**Issue by noobshow** [EthWorks/useDApp#201]
Hi,
Been using this library(big time-saver) in production and been noticing some issues(either from my side or the library) i can't pinpoint.

My thoughts :

useMemo isn't the best solution for comparing objects returned from contract calls and BigNumber object as it uses Object.is() which is known to not make deep-comparison..

Solution Proposed :
If for it, we can change the whole useMemo call to a better alternative i found on the web
[https://github.com/kotarella1110/use-custom-compare#usecustomcomparememo](useCustomCompareMemo) which implements a compare(prev, next) => boolean callback to deep compare the returned values to avoid unnecessary re-renders on user's components

I can in my spare time quickly work on this and we run tests to be sure all is when, before fully merging

**Comment by noobshow** [comment]
I noticed my tests since after using this comparable memo now looks more straightforward and hardly do I notice any unnecessary rerender coming from useDapp

**Comment by noobshow** [comment]
Is this up for discussion?
I can close the issue if it's not, I can still use the useCompareMemo in my project to avoid udeDapp from rerendering my components when there isn't any change to render

**Comment by marekkirejczyk** [comment]
I would open this for discussion. It is a worthy consideration.

**Comment by noobshow** [comment]
There are various libraries to make that work, going for such dependency or just bringing in a slim one file hook?

**Comment by noobshow** [comment]
Read this [SO QA](https://stackoverflow.com/a/54096391/5333331) to see the bug(shouldn't say bug, but its surprisingly a bug).

**Comment by noobshow** [comment]
@marekkirejczyk should I open a pull request for this in a tiny, sketchy little hook that will add alternatives to `useCallback, useMemo, useEffect` that can be used in places where objects are involved, e.g `useTokenBalance, useEtherBalance`, etc so that the repeated block checks won't affect the the components calling the context hooks whenever there's nothing changed?

**Comment by noobshow** [comment]
Hi @marekkirejczyk,
Seems this has been solved somewhere?

**Comment by wminshew** [comment]
this makes sense to me. Noticed I can't use library as a dependency for effects/callbacks (even tho it looks like useDapp uses it in the useLookupAddress hook)--would this help with that? Or should I stick to just using account, chainId etc?

**Comment by noobshow** [comment]
My suggestion above works to prevent state changes that doesn't change any of the object data to redraw my react components...

**Comment by noobshow** [comment]
Instead of usedapp redrawing my components on every new blocks, the components only get redrawn when data changes.
