### ISSUE TITLE
NotificationsProvider not exported.

### ISSUE THREAD

**Issue by brunitob** [EthWorks/useDApp#209]
'NotificationsProvider' is not exported from '@usedapp/core' 
Im using my own `Web3ReactProvider`  and I want to reuse the `DAppProviderWithConfig` but with my own implementation of the web3provider, changing `EthersProvider` for my own provider. Its there a way to do that?

**Comment by marekkirejczyk** [comment]
No reason not to export NotificationsProvider, feel free to create PR.
What is the goal of using your own Web3Provider? The easiest way that comes to mind is to "extend it", i.e. create new base on the current one.

**Comment by brunitob** [comment]
Not a really good reason. Just a production project with a Web3Provider implementation. 
But was easier to migrate to useEthers()

**Comment by marekkirejczyk** [comment]
Migration is a good reason. We will have to think about it some more. However now priority is to get base functionality done.
