### ISSUE TITLE
Handle network change issue.

### ISSUE THREAD

**Issue by brandonchuah** [EthWorks/useDApp#224]
Hey there!
I am having problems with network changing after adding custom networks. 

Here is my config: 
<img width="771" alt="Screenshot 2021-05-21 at 12 50 36 PM" src="https://user-images.githubusercontent.com/73574416/119083755-257d5000-ba33-11eb-880b-390110ac6196.png">

On some instances, there would be no issue. 
<img width="323" alt="Screenshot 2021-05-21 at 12 42 59 PM" src="https://user-images.githubusercontent.com/73574416/119083295-44c7ad80-ba32-11eb-8633-97bd4d57dfcf.png">
I am using the effect hook to print out the chainId and provider from useEthers() if there is a change.
 
Sometimes I would get 
<img width="319" alt="Screenshot 2021-05-21 at 12 26 12 PM" src="https://user-images.githubusercontent.com/73574416/119083532-b56eca00-ba32-11eb-923c-f1442efb9f31.png"> 
chainId, library, provider from useEthers() are not being updated as well.

Also it would get disconnected as well.
<img width="327" alt="Screenshot 2021-05-21 at 12 40 13 PM" src="https://user-images.githubusercontent.com/73574416/119083658-f1a22a80-ba32-11eb-8e80-5476756cd687.png">

Please advise thank you very much.

**Comment by marekkirejczyk** [comment]
You need to add ChainId to useDApp to be able to use it. See example PR [here](https://github.com/EthWorks/useDApp/commit/21f59f6f80bc9307abaa1dc3cb6e17230b77899f).
Also it won't work without multicall deployed and configured.

**Comment by brandonchuah** [comment]
I am still facing this issue after adding the specs to ChainId and deploying multicall. I tried removing my config but i still face the same error when i switch to xDai. The other Ethereum networks are fine. I believe a default config is used if one is not provided which supports xDai.

**Comment by npasquie** [comment]
Hello same here, replicated the PR but can't make it work on Fantom. Why not allow the developer to configure whatever chain he chooses ???

**Comment by rajnishtech** [comment]
How do add my custom chain id to connect my private network?

**Comment by tt-marek** [comment]
Continuation in #408
