### ISSUE TITLE
isTestChain is backwards at least in the documentation

### ISSUE THREAD

**Issue by PatrickAlphaC** [EthWorks/useDApp#228]
<img width="338" alt="Screen Shot 2021-05-22 at 11 59 14 AM" src="https://user-images.githubusercontent.com/54278053/119233041-28407980-baf5-11eb-9435-c72a8dadde80.png">

https://usedapp.readthedocs.io/en/latest/core.html?highlight=ChainId.Mainnet#istestchain

**Comment by marekkirejczyk** [comment]
Fixed:
https://usedapp.readthedocs.io/en/latest/core.html#istestchain
