### ISSUE TITLE
Handle block number - ethers block number vs fetched block number

### ISSUE THREAD

**Issue by rzadp** [EthWorks/useDApp#23]
There is a difference between a block number coming from `useBlockNumber`, and the block number of last successfully fetched number.

The difference surfaces here:

https://github.com/EthWorks/dapp-boilerplate/blob/8cccf7082d98c5d314d6d4ff050faa0ce759fb43/packages/ui/src/components/page/BlockNumber.tsx#L11-L12

It should be clear what a block number means and which one to use.
Perhaps only the fetched block number should be exposed to the end user of `useDapp`? i.e. add block number to `useBlockMeta` and do not expose `useBlockNumber`?

**Comment by tt-marek** [comment]
`useBlockNumber()` - triggers when new block arrives (triggers first)
`useChainState()?.value?.blockNumber` - changes after multicall was issued and values are updated (triggers later)

Second could be considered private implementation detail of multicall feature
