### ISSUE TITLE
Ethersjs version is not matched internally 

### ISSUE THREAD

**Issue by wildmouse** [EthWorks/useDApp#231]
Hi, awesome project here!

usedapp/core assumes ethers version is `5.1.4`, but ethers actually use `5.2.0` versions internally. 

Its reproducible with trying to build repo's example project, following error occurred. 

```
$ yarn build
yarn run v1.22.10
$ tsc --noEmit && rimraf build && webpack --mode production --progress
src/components/Transactions/Forms.tsx:12:52 - error TS2345: Argument of type 'Interface' is not assignable to parameter of type 'ContractInterface'.
  Property 'getError' is missing in type 'import("/Users/wildmouse/ghq/github.com/ethworks/usedapp/packages/example/node_modules/@ethersproject/abi/lib/interface").Interface' but required in type 'import("/Users/wildmouse/ghq/github.com/ethworks/usedapp/packages/example/node_modules/@ethersproject/contracts/node_modules/@ethersproject/abi/lib/interface").Interface'.

12 const contract = new Contract(wethContractAddress, wethInterface)
                                                      ~~~~~~~~~~~~~

  node_modules/@ethersproject/contracts/node_modules/@ethersproject/abi/lib/interface.d.ts:53:5
    53     getError(nameOrSignatureOrSighash: string): ErrorFragment;
           ~~~~~~~~
    'getError' is declared here.


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Szymx95** [comment]
We will probably bump ethers version to `5.2.0` but for now you can add resolutions to package.json in you projects

```
  "resolutions": {
    "@ethersproject/abi": "5.1.2",
    "@ethersproject/contracts": "5.1.1"
  }
```

The problem actually lies with `ethers 5.1.4` itself.
Right now if you use simple project  like 
```
import { utils, Contract } from 'ethers'
import * as WethAbi from './Weth10.json'
const wethInterface = new utils.Interface(WethAbi)
const wethContractAddress = '0xA243FEB70BaCF6cD77431269e68135cf470051b4'
const contract = new Contract(wethContractAddress, wethInterface)
```
will fail.

if you go to [https://github.com/ethers-io/ethers.js/blob/v5.1.4/packages/contracts/package.json](url) you will see that `@ethersproject/contracts 5.1.1` depends on `"@ethersproject/abi": "^5.1.0"` and that includes `@ethersproject/abi 5.2.0` which adds `getError` function.

But `ethers 5.1.4` contains :
`@ethersproject/contracts 5.1.1` which internally uses `@ethersproject/abi 5.2.0` 
`@ethersproject/abi 5.1.2`

Ethers js should have been using `"@ethersproject/abi": "~5.1.0"` in it's internal dependencies

**Comment by marekkirejczyk** [comment]
We will add note to docs and release update to docs soon.

**Comment by marekkirejczyk** [comment]
Added section here:
https://usedapp.readthedocs.io/en/latest/getting-started.html#troubleshooting
