### ISSUE TITLE
Returning more accurate errorMessage

### ISSUE THREAD

**Issue by quagliero** [EthWorks/useDApp#260]
Hi - love useDapp, has simplified my workflow massively.

One thing I've found is that metamask will throw relevant errors in the console, but the `state.errorMessage` will always defer to a default "cannot estimate gas". (see pictures)

Is there a way for the `state` object of contract interaction hooks to return this error message?

![Screenshot 2021-06-05 at 11 25 24](https://user-images.githubusercontent.com/4254570/120888674-85f2bc80-c5f1-11eb-9d38-d8ba7ff55812.png)

**Comment by suniljmishra** [comment]
This is necessary, so that contract level error codes can be handled. Please fix asap.

**Comment by eliotmess** [comment]
Same here, proper error handling is one of the things I miss the most to call useDApp a perfect tool.

**Comment by quagliero** [comment]
OK I think I've found a way to get these, will create a PR, but in case I can't get to it soon or someone else stumbles across it/wants to do it first:

https://github.com/EthWorks/useDApp/blob/master/packages/core/src/hooks/usePromiseTransaction.ts#L26

usePromiseTransaction, in the catch, `e.error` actually contains all the info you see from MetaMask in the console. Probably just want to check if e.error exists too and use that if possible.

![Screenshot 2021-07-21 at 13 28 13](https://user-images.githubusercontent.com/4254570/126488326-ba07d267-c0ea-4347-b942-843b91d3ebd9.png)
