### ISSUE TITLE
Cannot disconnect

### ISSUE THREAD

**Issue by MrNithi** [EthWorks/useDApp#273]
After disconnect when the user refreshes the page The connection is still connected

**Comment by quagliero** [comment]
I have noticed this started happening too after I upgraded the app. I believe it was introduced with the https://github.com/EthWorks/useDApp/commit/b3697743581b7c06f9515fb8b3e988696463ffea commit that handled persistent connection.

While the persistent connection needs to happen for refreshes etc, if you call the `deactivate` function it should kill this from happening, and it doesn't.

We ended up doing some hacks setting localStorage items when you disconnect, and checking if they exist on page load, and if they are, then running `deactivate` again... but it's certainly not ideal.

**Comment by josh-richardson** [comment]
I'm also encountering this

**Comment by kalanyuz** [comment]
I think this is not useDApp's fault but rather web3-react's, which they pulls `deactivate` function from. There's also an open issue over there: https://github.com/NoahZinsmeister/web3-react/issues/228 and so far it's not yet fixed.

**Comment by jontonsoup** [comment]
this seems like a major security issue. what is the suggestion for mitigating it?

**Comment by trozler** [comment]
Any idea on how to mitigate this ?
Finding this to be quite annoying

**Comment by MatthewTang** [comment]
any updates ? also facing the same problem, thanks !

**Comment by tt-marek** [comment]
This is Metamask issue, should be solvable with #385
