### ISSUE TITLE
Metamask JSON-RPC provider error: exhausted retries

### ISSUE THREAD

**Issue by kyriediculous** [EthWorks/useDApp#274]
Upon initial page load I get a JSON-RPC provider error and none of my RPC requests make it through. 

```
inpage.js:1 MetaMask - RPC Error: BlockReEmitMiddleware - retries exhausted 
```

The affected code seems to be a custom hook which wraps a `useContractCall`. For context, this hook calculates the amount of balancer liquidity pool tokens a user should receive based on his current inputs. 

```tsx
    // Contract Functions
    const useCalcSinglePoolOut = () => {
        let tokenIn: BigNumberish = 0
        let tokenInBal: BigNumberish = 0
        let weight: BigNumberish = 0
        if (selectToken === symbol) {
            tokenIn = utils.parseEther(tokenInput||"0")
            tokenInBal = tokenLpBalance||"0"
            weight = tokenWeight||"0"
        } else {
            tokenIn = utils.parseEther(tenderInput||"0")
            tokenInBal = tenderLpBalance||"0"
            weight = tenderTokenWeight||"0"
        }

        return useContractCall({
            abi: contracts[name].swap.interface,
            address: addresses[name].swap,
            method: 'calcPoolOutGivenSingleIn',
            args: [tokenInBal, weight, lpShares||"1", totalWeight||"1", tokenIn, swapFee]
        })
    }
```

The hook is simply used as follows:

```tsx
    const singlePoolOut = useCalcSinglePoolOut()||"0"
```

Here's where things get weird. 

1. When I remove the call to `useCalcSinglePoolOut()` the page loads fine with all RPC calls succeeding. When I then re-add the hook and have the page hot-reload in local development I can make a transaction successfully using the value from this hook as an argument just fine. 

2. Now since this is a contract call and not a function that requires signing through the inpage provider (metamask) it should use the readOnlyProvider (which is infura for this app), so I'm wondering why the error is tagged with `MetaMask`. 

It might be likely that the call upon pageload contains data that might lead to an EVM exception but then the returned error still seems weird. 

Any ideas ? Thanks !

**Comment by kyriediculous** [comment]
Validating the data worked, but the error handling was confusing

**Comment by sunilmishradev** [comment]
@kyriediculous What did you to resolve this issue?
