### ISSUE TITLE
Read-only methods

### ISSUE THREAD

**Issue by BitWonka** [EthWorks/useDApp#279]
How to get read-only methods from contracts? 

for example from ethers docs 

```// Get the ERC-20 token name
await daiContract.name()
// 'Dai Stablecoin'

// Get the ERC-20 token symbol (for tickers and UIs)
await daiContract.symbol()
// 'DAI'```

**Comment by nezouse** [comment]
I guess that's what you are looking for: https://usedapp.readthedocs.io/en/latest/guide.html#reading-from-blockchain
