### ISSUE TITLE
"TypeError: Unsupported chain" calling useContractFunction

### ISSUE THREAD

**Issue by goneale** [EthWorks/useDApp#289]
Hi Team

Great framework. Can't seem to get past this one, no matter how I try. Fairly new to dApp design, but pretty sure I have everything setup right.

As soon as I call this,
```
const { state: buyTx, send: buyTest } = useContractFunction(contract, 'test', { transactionName: 'Buy test' });
buyTest();
```
I receive this via the:
```
useEffect(() => {
    console.log(buyTx);
  }, [buyTx]);
```

![image](https://user-images.githubusercontent.com/107109/126737617-4a971425-ec1b-480b-8d86-a1a2170bbd9e.png)
You can clearly see the `chainId=5` in the screenshot, this is Goerli and I can connect to my wallet OK to get this far.

I should also state, if I change my contract function to `buy1` for example,. it crashes stating `Unhandled Rejection (TypeError): contractWithSigner[functionName] is not a function` so I know it's communicating to the very simple buy method I have settup in Solidity (currently returning 123 as a uint256).

Thanks in advance

**Comment by goneale** [comment]
I should also state, if I change my contract function to `buy1` for example,. it crashes stating `Unhandled Rejection (TypeError): contractWithSigner[functionName] is not a function` so I know it's communicating to the very simple buy method I have settup in Solidity (currently returning 123 as a uint256).

**Comment by goneale** [comment]
After further inspection by console.logging in the code, it appears this destructure would never work, as chainId is never included in the object?
![image](https://user-images.githubusercontent.com/107109/126748527-c46cb912-24dc-4f8d-be57-c95c994ea157.png)

**Comment by goneale** [comment]
Hi team, can anybody help me with this please? :)

**Comment by kalanyuz** [comment]
Experiencing the same problem here. It seems like 
`await transactionPromise` in usePromiseTransaction is already resolved and is returning the result instead of the expected `StoredTransacton` object. Not sure if this happens only on local chain or not.

**Comment by kalanyuz** [comment]
@goneale I just use ethers + useState directly as a workaround instead for the time being. 
https://docs.ethers.io/v5/getting-started/#getting-started--contracts

Also willing to submit a PR if someone can point me where to look.

**Comment by leclercb** [comment]
Same problem here too.

**Comment by osengaa10** [comment]
I too am having this issue (on Goerli Testnet). Everything is working as it should on the blockchain and contract layer, but the UI crashes. 

![unsupportedChainError](https://user-images.githubusercontent.com/15097961/129785292-34e86f71-4ae5-4f5d-ac08-43b17f2fc46b.png)
![handlePurchaseKeys](https://user-images.githubusercontent.com/15097961/129785301-ed25eb15-a8d7-4a76-b015-5f34594653ba.png)

**Comment by ayushsharma-eth** [comment]
Just got this same error on Ropsten. In my case, it likely has to due with Metamask use EIP-1559 transactions. Yesterday, it was using Legacy type transactions and working fine.

**Comment by AlexBrandes** [comment]
I've been having the same issue since yesterday as well. Here's a workaround that seems to fix the issue. Basically, all we need to do is add the chainId to the result of the contract function. 

```
import { useCallback, useState } from 'react'
import { usePromiseTransaction } from '@usedapp/core/dist/esm/src/hooks/usePromiseTransaction'
import { Contract } from '@ethersproject/contracts'

export const useContractFunction = (
  contract: Contract,
  functionName: string,
  chainId: number | undefined,
  options?: { transactionName?: string }
) => {
  const [events, setEvents] = useState<Record<string, any> | undefined>(
    undefined
  )

  const { promiseTransaction, state } = usePromiseTransaction(chainId, options)

  const send = useCallback(
    async (...args: any[]) => {
      const sendPromise = contract[functionName](...args).then(
        (result: any): Promise<any> => {
          // Need to add chainId here to prevent "TypeError: Unsupported Chain" error message
          result.chainId = chainId
          return result
        }
      )

      const receipt = await promiseTransaction(sendPromise)

      if (receipt) {
        if (receipt.logs && receipt.logs.length > 0) {
          setEvents(receipt.logs.map((log) => contract.interface.parseLog(log)))
        } else {
          setEvents([])
        }
      }
    },
    [contract, functionName, options]
  )

  return { send, state, events }
}

```

**Comment by mortimr** [comment]
Hey Alex, thankd a lot for your workaround ! 

It wasn't working at first on my end because the contract instance wasn't connect to a signer, had to make some tweaks (also removed chainId as parameter and got it directly from useEthers)

```
import { useCallback, useState } from 'react'
import { usePromiseTransaction } from '@usedapp/core/dist/esm/src/hooks/usePromiseTransaction'
import { Contract } from '@usedapp/core/node_modules/ethers';
import { Web3Provider } from '@usedapp/core/node_modules/@ethersproject/providers';
import { TransactionOptions, useEthers } from '@usedapp/core';
import { Signer } from 'ethers';

export function connectContractToSigner(contract: Contract, options?: TransactionOptions, library?: Web3Provider) {
  if (contract.signer) {
    return contract
  }

  if (options?.signer) {
    return contract.connect(options.signer as Signer)
  }

  if (library?.getSigner()) {
    return contract.connect(library.getSigner())
  }

  throw new TypeError('No signer available in contract, options or library')
}

export const useContractFunction__fix = (
  contract: Contract,
  functionName: string,
  options?: TransactionOptions
) => {
  const { library, chainId } = useEthers()
  const [events, setEvents] = useState<Record<string, any> | undefined>(
    undefined
  )

  const { promiseTransaction, state } = usePromiseTransaction(chainId, options)

  const send = useCallback(
    async (...args: any[]) => {
      const contractWithSigner = connectContractToSigner(contract, options, library)
      const sendPromise = contractWithSigner[functionName](...args).then(
        (result: any): Promise<any> => {
          // Need to add chainId here to prevent "TypeError: Unsupported Chain" error message
          result.chainId = chainId
          return result
        }
      )

      const receipt: any = await promiseTransaction(sendPromise)

      if (receipt) {
        if (receipt.logs && receipt.logs.length > 0) {
          setEvents(receipt.logs.map((log) => contract.interface.parseLog(log)))
        } else {
          setEvents([])
        }
      }
    },
    [contract, functionName, chainId, promiseTransaction, library, options]
  )

  return { send, state, events }
}

```

**Comment by mortimr** [comment]
Also if anyone needs `useSendTransaction`
```
import { TransactionRequest } from '@ethersproject/abstract-provider'
import { TransactionOptions, useEthers } from '@usedapp/core';
import { usePromiseTransaction } from '@usedapp/core/dist/esm/src/hooks/usePromiseTransaction';

export function useSendTransaction__fix(options?: TransactionOptions) {
  const { library, chainId } = useEthers()
  const { promiseTransaction, state } = usePromiseTransaction(chainId, options)

  const sendTransaction = async (transactionRequest: TransactionRequest) => {
    const signer = options?.signer || library?.getSigner()
    if (signer) {
      await promiseTransaction(
        signer.sendTransaction(transactionRequest)
          .then(
            (tx: any) => {
              tx.chainId = chainId
              return tx;
            }
          )
      )
    }
  }

  return { sendTransaction, state }
}
```

**Comment by quagliero** [comment]
Thanks for these @mortimr  @AlexBrandes, was wondering why in last 24hours the app randomly started crashing. Hopefully useDapp can get a fix released asap.

**Comment by derekbar90** [comment]
This is due to an update of Metamask to start doing type 2 transactions (EIP1559 transactions)

**Comment by derekbar90** [comment]
Ethers pushed support but it seems useDapp is using a pinned older version of ethers

https://github.com/ethers-io/ethers.js/blob/master/CHANGELOG.md#ethersv540-2021-06-26-0150

https://github.com/EthWorks/useDApp/blob/master/packages/core/package.json#L41

**Comment by quagliero** [comment]
@derekbar90 I wonder if using a `resolution` in your app’s package.json using the latest ethers version would fix this temporarily while useDapp fixes.

**Comment by nezouse** [comment]
Hi, i fixed the issue with chainId being equal 0, it's up in version 0.4.5

**Comment by drewspanning** [comment]
This still seems to be an issue for Avalanche Fuji contract calls
