### ISSUE TITLE
Events Support

### ISSUE THREAD

**Issue by adamskrodzki** [EthWorks/useDApp#296]
Does UseDapp has any supports of Events 
eg reading events emmited by specific contract ?

**Comment by marekkirejczyk** [comment]
Yes `useContractFunction` and `useSendTransaction` returns `{events, ...}`.
See: https://usedapp.readthedocs.io/en/latest/core.html#usecontractfunction

**Comment by adamskrodzki** [comment]
Hi thanks for answer,
but I initially intended wider question:

Can I observe for events send by others ?
For instance scan for all Transfer events of particular token no matter who initiated them?

**Comment by marekkirejczyk** [comment]
General event observation is a hard topic, you probably want to use [The Graph](https://thegraph.com/)
