### ISSUE TITLE
Error when useContractFunction on Binance Smart Chain Testnet ?

### ISSUE THREAD

**Issue by ppirch** [EthWorks/useDApp#297]
I implement my DApp with useDApp. Now I try to set config with this code.
```
const config: Config = {
  readOnlyChainId: 97,
  readOnlyUrls: {
    97: "https://data-seed-prebsc-1-s1.binance.org:8545/",
  },
  multicallAddresses: {
    97: "0xae11C5B5f29A6a25e955F0CB8ddCc416f522AF5C",
  },
  supportedChains: [97],
}
     
```

It works for useEthers, useEtherBalance, useTokenBalance, useContractCall, useTokenAllowance. Their state work normally , But when I try to useContractFunction then after create transaction. It says `Uncaught TypeError: Unsupported chain | The above error occurred in the <TransactionProvider> component:` 

How can I fix it? or contribute for add new network.

**Comment by ppirch** [comment]
I try to add bsc testnet network in 
  @usedapp/core/src//helpers/chain.ts
  @usedapp/core/src/constants/chainId.ts
  @usedapp/core/src/model/config/default.ts
When I run useContractFunction again it's work but is this the right way to do that?

**Comment by kunalalite** [comment]
It would be nice if someone could confirm that if the above approach is valid for operating with a new change using useDapp.

**Comment by tt-marek** [comment]
BSC should work out of the box with #353
