### ISSUE TITLE
Getting token balances on other chains returns undefined

### ISSUE THREAD

**Issue by tskweres** [EthWorks/useDApp#303]
I'm using the tutorial to get token balances on ETH Mainnet and it works great, but if I switch to Polygon for example, I get back an array of undefineds.

`

export function useTokensBalance(tokenList: any[], account?: string | null) {
  return useContractCalls(
    tokenList && account
      ? tokenList.map((token: any) => ({
          abi: ERC20_INTERFACE,
          address: token.address,
          method: 'balanceOf',
          args: [account],
        }))
      : []
  )
}

`

**Comment by tt-marek** [comment]
You need to filter tokens by chainId. The same tokens does not exist on multiple chains. 
There might be equivalents, but most of the time with different addresses.
