### ISSUE TITLE
Jest?

### ISSUE THREAD

**Issue by jontonsoup** [EthWorks/useDApp#306]
Is there an example of how to test with jest and react testing library? I'm confused how you are supposed to test the components here?

Thanks!
Jon

**Comment by RyanRHall** [comment]
@jontonsoup I don't believe useDApp ships with any native testing features. It's more of an add-on to include with your pre-existing react app. You can pair it pretty seamlessly with [create-react-app](https://create-react-app.dev/), which will provide you with a testing framework, among other things.

**Comment by jontonsoup** [comment]
So what I mean by this is 1. lack of examples  2. what is the suggested paradigm? 

From what I can tell the idea is to test hooks and then mock out the hooks in the react tests. Does that sound right?

**Comment by tt-marek** [comment]
No plans to support Jest. 
For testing hooks check [docs](https://usedapp.readthedocs.io/en/latest/guide.html#testing-hooks) and this [blog post](https://medium.com/ethworks/usedapp-deep-dive-into-custom-hooks-and-testing-4a59fbc1769a)
