### ISSUE TITLE
Unsupported chain when using useDapp + Metamask 10.0.2

### ISSUE THREAD

**Issue by mortimr** [EthWorks/useDApp#308]
Hi,

since this morning I'm unable to make useDapp work properly with Metamask 10.0.2. Every single time I broadcast a transaction, it gets sent to MM and to the rpc, but useDapp is crashing.
I'm running a local mainnet fork on chainId 1, it has been working properly for weeks (even yesterday)

It's due to this check https://github.com/EthWorks/useDApp/blob/67253dd3057f60d01439e42fcfeb295363e777de/packages/core/src/providers/transactions/reducer.ts#L25

Anyone else has this issue ? Any insights on what MM might have changed in 10.0.2 ?

**Comment by mortimr** [comment]
![Screenshot 2021-08-19 at 10 38 10](https://user-images.githubusercontent.com/17824082/130036992-35e53312-0191-471b-a2cb-46a87387280a.png)
It seems like Metamask is sending a payload with `chainId: 0` for some reason

**Comment by vujevits** [comment]
I have the same issue when using `rinkeby`

**Comment by AlexBrandes** [comment]
Related: #289 

Workaround: https://github.com/EthWorks/useDApp/issues/289#issuecomment-901919942
