### ISSUE TITLE
Missing `lodash` dependency

### ISSUE THREAD

**Issue by jjperezaguinaga** [EthWorks/useDApp#321]
## Expected behavior

I'm able to install `@usedapp/core` without any issues.

## Current behavior

Installing `@usedapp/core@0.4.7` throws a `Module not found: Can't resolve 'lodash'` error.

![image](https://user-images.githubusercontent.com/1128312/131947897-bca0691d-fac3-4601-a420-d44c415e9022.png)

## Possible solution

Remove `lodash` dependency and use `Object.assign` instead of `merge`, which is only used [once](https://github.com/EthWorks/useDApp/blob/0011fe5e4428cb37f6efa870728e93e7cbff108f/packages/core/src/providers/config/reducer.ts#L2). Alternatively, include `lodash` in your `package.json` dependency, as it seems that just adding `@types/lodash` might not be enough.

## Steps to reproduce

1. `mkdir tmp && cd $_ && npm init -y && npm install @usedapp/core@0.4.7`
2.  See `lodash` missing in `node_modules`

## Context

I was trying to use `@usedapp/core` in a new project and not the usual scaffold I usually use, so for the first time I was using `latest`. Then my server showed the error. I couldn't help to notice that #249 added `lodash` in [here](https://github.com/EthWorks/useDApp/pull/249/files#diff-037b0ef349d759ea867ae708d180ef398f4b15147563bf8469b91df339f4cb02R5) but didn't add it on package.json. This was likely not picked up because it's such a common dependency that it's likely within another dependency. Oddly enough, though, this could had been picked up with a CI system or a simple GitHub action to build the project.

## Additional comments

Installing `lodash` in my project as a dependency solves the issue, but that seems like a patch rather than solving the actual problem. Also, we could just import `lodash.merge` instead of the whole thing. FWIW I went down versions as low as `0.4.1` and kept stumbling across this problem. Considering the constant updates and vulnerabilities that `lodash` keeps showing (or at least for how often I get spammed by Dependabot across my multiple projects), I would try to stir away from it in the future unless strickly necessary.

**Comment by nezouse** [comment]
Just to confirm, you are using npm v7?

**Comment by jjperezaguinaga** [comment]
Thanks!
