### ISSUE TITLE
[question] how to know when transaction was "sent" to wallet?

### ISSUE THREAD

**Issue by maraoz** [EthWorks/useDApp#331]
Hi! I'm using useDApp for the first time. So far, so good! A much better experience than doing everything by hand.

I have a question: what's the recommended way of knowing when a transaction request was sent to metamask, but was still not signed? 

I'm currently doing something like:
```js
function SomePage() {
  const { account, library} = useEthers();
  const [walletOpened, setWalletOpened] = useState(false);
  const { sendTransaction, state } = useSendTransaction({ transactionName: 'Send Ethereum' })
  ... 
  const sendHandler = async function() {
    if (!account) return;
    const amountWEI = ethers.utils.parseEther("1.0");
    sendTransaction({ to: address, value: amountWEI})   
    setWalletOpened(true);
  }
  ...
  return <Button onClick={sendHandler} isLoading={walletOpened}>Send</Button>
}  
```

But I was wondering if there is built-in support for something like this from the framework. I couldn't find anything in the docs. Thanks!

**Comment by noobshow** [comment]
Aren't those information supposed to be in `state` None, Mining, etc?

**Comment by tt-marek** [comment]
@noobshow exactly
See [docs](https://usedapp.readthedocs.io/en/latest/guide.html#transactions)

**Comment by maraoz** [comment]
What's the state that indicates a tx being sent to metamask before it was
approved by the user?

**Comment by noobshow** [comment]
You can debug it by using useEffect to check what changed within the state then see what it's at whenever it get sent to Metamask.
I think that's still gotta be None, since Mining indicates the transaction being sent to node
