### ISSUE TITLE
[question] how to catch metamask errors correctly

### ISSUE THREAD

**Issue by maraoz** [EthWorks/useDApp#337]
Hi, I'm polishing my first useDApp application, and looking to catch some edge case errors to handle in my app, for example:
- when there's no internet connection
- when metamask fails to connect to the rpc node (eg: because my development node or the provider (infura) are down)

What's the recommended way to do this? I expected the `error` returned in 
```
const { account, error } = useEthers();
```
but it's `undefined` in all these scenarios, but I see errors in the browser console. Any ideas? Thanks!

**Comment by tt-marek** [comment]
Check the [doc](https://usedapp.readthedocs.io/en/latest/guide.html#handling-wallet-activation-errrors) first and let me know if it helps. Closing for now, feel free to reopen.
