### ISSUE TITLE
An "official" example of using useDapp with "Web3Modal" in the useDapp docs would increase adoption a lot

### ISSUE THREAD

**Issue by JayWelsh** [EthWorks/useDApp#345]
I think having this would enable a lot more adoption of useDapp

**Comment by chrishol** [comment]
+1 this would be extremely helpful!

**Comment by JayWelsh** [comment]
cc: @nezouse @quagliero @marekkirejczyk 

Seems to be some interest here, just letting you know. 🌈 🙏

**Comment by tt-marek** [comment]
It is in the backlog, no specific target date thou

**Comment by JayWelsh** [comment]
Thanks a lot @tt-marek !

**Comment by alexiskattan** [comment]
I am trying to make this work but am having issues with it.  Here is the minimal code.  It works for MetaMask but not for WalletConnect or Formatic.  

```
export default function ConnectButton({ handleOpenModal }: Props) {
  // const { activateBrowserWallet, account } = useEthers();
  // const { activate } = useEthers()
  const {activateBrowserWallet, account, chainId, active, activate, deactivate} = useEthers()

  async function handleConnectWallet() {
    const provider = await web3Modal.connect();
    const ethersProvider = new ethers.providers.Web3Provider(provider);
    const ethersSigner = ethersProvider.getSigner();
    activate(provider)
  }
}
```

I think the issue is with the `activate(provider)` part.  I'm not sure how to tell useDapp that I want to use a specific `ethersProvider` and `ethersSigner`.  If anyone has any place to take it from here or could correct my mis-understanding it would be helpful.

**Comment by kesar** [comment]
+1

**Comment by noobshow** [comment]
> I am trying to make this work but am having issues with it. Here is the minimal code. It works for MetaMask but not for WalletConnect or Formatic.
> 
> ```
> export default function ConnectButton({ handleOpenModal }: Props) {
>   // const { activateBrowserWallet, account } = useEthers();
>   // const { activate } = useEthers()
>   const {activateBrowserWallet, account, chainId, active, activate, deactivate} = useEthers()
> 
>   async function handleConnectWallet() {
>     const provider = await web3Modal.connect();
>     const ethersProvider = new ethers.providers.Web3Provider(provider);
>     const ethersSigner = ethersProvider.getSigner();
>     activate(provider)
>   }
> }
> ```
> 
> I think the issue is with the `activate(provider)` part. I'm not sure how to tell useDapp that I want to use a specific `ethersProvider` and `ethersSigner`. If anyone has any place to take it from here or could correct my mis-understanding it would be helpful.

You shouldn't be connecting Web3Provider to `activate` function, you should get the name of the wallet from web3Modal and get a connector for it, i don't know much about web3Modal, but this is the idea :

```javascript
// import { TorusConnector } from '@web3-react/torus-connector'
// import { FortmaticConnector } from '@web3-react/fortmatic-connector'

          if (wallet.type === 'injected') {
            const injected = new InjectedConnector({
              supportedChainIds: [
                ChainId.Mainnet,
                ChainId.Kovan,
                ChainId.Localhost
              ]
            })
            activate(injected)
          } else if (wallet.type === 'hardware') {
            if (wallet.name === 'walletConnect') {
                const walletconnect = new WalletConnectConnector({
                   rpc: { 1: RPC_URLS[1] },
                   qrcode: true,
                   pollingInterval: POLLING_INTERVAL
                 })
             activate(walletconnect)
            }
          }
        }
```

I pray and hope you get the idea, but that works for me in various other cases, you still have to persist the connection onLoad somehow

**Comment by yukydev** [comment]
> > I am trying to make this work but am having issues with it. Here is the minimal code. It works for MetaMask but not for WalletConnect or Formatic.
> > ```
> > export default function ConnectButton({ handleOpenModal }: Props) {
> >   // const { activateBrowserWallet, account } = useEthers();
> >   // const { activate } = useEthers()
> >   const {activateBrowserWallet, account, chainId, active, activate, deactivate} = useEthers()
> > 
> >   async function handleConnectWallet() {
> >     const provider = await web3Modal.connect();
> >     const ethersProvider = new ethers.providers.Web3Provider(provider);
> >     const ethersSigner = ethersProvider.getSigner();
> >     activate(provider)
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think the issue is with the `activate(provider)` part. I'm not sure how to tell useDapp that I want to use a specific `ethersProvider` and `ethersSigner`. If anyone has any place to take it from here or could correct my mis-understanding it would be helpful.
> 
> You shouldn't be connecting Web3Provider to `activate` function, you should get the name of the wallet from web3Modal and get a connector for it, i don't know much about web3Modal, but this is the idea :
> 
> ```js
> // import { TorusConnector } from '@web3-react/torus-connector'
> // import { FortmaticConnector } from '@web3-react/fortmatic-connector'
> 
>           if (wallet.type === 'injected') {
>             const injected = new InjectedConnector({
>               supportedChainIds: [
>                 ChainId.Mainnet,
>                 ChainId.Kovan,
>                 ChainId.Localhost
>               ]
>             })
>             activate(injected)
>           } else if (wallet.type === 'hardware') {
>             if (wallet.name === 'walletConnect') {
>                 const walletconnect = new WalletConnectConnector({
>                    rpc: { 1: RPC_URLS[1] },
>                    qrcode: true,
>                    pollingInterval: POLLING_INTERVAL
>                  })
>              activate(walletconnect)
>             }
>           }
>         }
> ```
> 
> I pray and hope you get the idea, but that works for me in various other cases, you still have to persist the connection onLoad somehow.
> 
> If you can't get it to work, i can check out web3Modal and post a full example here in Typescript

Hey would be interested in having the full example :) Thanks in advance for your help

**Comment by noobshow** [comment]
Checked web3Modal, it prefers Providers instead which is somehow difficult to implement directly with this current useDapp version...

FYI, just yesterday i noticed a merge that might change the problem, especially in regards to setting provider and connector aside using `activate` function in https://github.com/EthWorks/useDApp/pull/479 PR, check the files and you can **see the example to work with web3Modal is there**, i think that PR is unfinished

**Comment by marekkirejczyk** [comment]
Hi All,

We recognise this as important feature.

We are working now on a series of cross-dependent features and refactorings, including:
- remove web3react dependency #491
- add example for Web3Dialog (draft in #489)
- enable multichain support

There might be major changes to framework and it might take a bit more time. Thank you for your patience.

**Comment by yukydev** [comment]
Hi Thanks for the answers @noobshow @marekkirejczyk 

For now I created my own model with web3-react for multi wallet connexion

Thanks for your help

**Comment by hiro00125** [comment]
Hi Everybody,
I'm struggling with web3modal integration in my useDApp based app. Have any of you tried it?

**Comment by tt-marek** [comment]
There is a new version released: 0.10 with working example with web3Modal.

App here:
https://example.usedapp.io/balance

Source here:
https://github.com/EthWorks/useDApp/blob/master/packages/example/src/components/account/Web3ModalButton.tsx

**Comment by hiro00125** [comment]
Thanks for your help!

**Comment by hiro00125** [comment]
I have another question. How can I make my own web3modal using useDapp?

**Comment by tt-marek** [comment]
Take a look at Connector example that uses web3react connectors to connect to various different wallets:
https://example.usedapp.io/web3react

**Comment by hiro00125** [comment]
Can you share your discord id?

**Comment by hiro00125** [comment]
![image](https://user-images.githubusercontent.com/86695188/151448035-70e6b8d6-1294-4c95-bccc-2ab17ce48d79.png)

**Comment by hiro00125** [comment]
I was trying to connect the web3modal, but it has an issue like that.

**Comment by tt-marek** [comment]
@vanruch Would you investigate?

**Comment by noobshow** [comment]
> ![image](https://user-images.githubusercontent.com/86695188/151448035-70e6b8d6-1294-4c95-bccc-2ab17ce48d79.png)

Do you install and import the Connector you were activating?
One of the connectors are InjectedConnector, you can check web3-react repo for more

**Comment by hiro00125** [comment]
The issue is because of the usedapp's version. I updated it to v0.10.0, and it works well.

**Comment by JayWelsh** [comment]
Hi @tt-marek & @vanruch, 

Firstly, thanks so much for making this change! I think this is going to help a lot with the adoption of useDapp!

I just wanted to raise that it seems that there might be one small thing worth looking into, consider the following situation (assume that this is using Web3ModalButton.tsx from the example implementation):

1. User clicks "connect"
2. User selects "WalletConnect" from the Web3Modal
3. User clicks the top-right "x" of the WalletConnect modal opened by Web3Modal

Closing the WalletConnect modal in this fashion leads to an unhandled error (in the example implementation you can see the error printed out into the console), it seems that this error needs to be handled within `@useDapp/core` itself, unless I am maybe missing a good place to handle it outside of the library.

Thanks again!

Peace.

**Comment by JayWelsh** [comment]
Another thing I would like to add is that when using the Web3ModalButton.tsx, even when connecting to MetaMask through it, when switching networks (e.g. Rinkeby <-> Mainnet), the client now shows an error (it handles network switches smoothly with the original "connect" button on https://example.usedapp.io/balance).

![Screenshot 2022-01-31 at 18 02 52](https://user-images.githubusercontent.com/14224459/151828901-993da48e-04a1-403d-bed3-3454b8dc5562.png)

**Comment by marekkirejczyk** [comment]
@vanruch Perhaps a better error handling in example?

**Comment by ryanchanplc** [comment]
Hi guys , 

currently i am using usedApp @ v0.10.1 with web3-react/walletconnect-connector @v.6.2.10. but i am facing an error when try to activate the walletconnect connector.

`walletconnect-connector.esm.js:238 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'connected')`

Any idea? Thanks
