### ISSUE TITLE
useContractCall returning undefined when value exists

### ISSUE THREAD

**Issue by Dylan-Kerler** [EthWorks/useDApp#347]
```
    const [tokenURI] =
        useContractCall({
            abi: new utils.Interface(NFT.abi),
            address: "0x1a92f7381b9f03921564a437210bb9396471050c",
            method: "tokenURI",
            args: [10],
        }) || [];
```

Expected to get: https://api.coolcatsnft.com/cat/10
Actually got: undefined

I can see that this NFT definitely exists here: https://etherscan.io/address/0x1a92f7381b9f03921564a437210bb9396471050c#readContract

Why am I getting undefined?

**Comment by Dylan-Kerler** [comment]
I had another useContractCall hook that was throwing an error in another component. After fixing the error there, I now get the result here. Apparently all useContractCall hooks have to be successful for them to work.

**Comment by robmi10** [comment]
Hi Dylan i have the same issue i want to return a simple value from my smart contract "uint256 public newbalance = 10;"
i use this hook which is also my only useContractCall hook in any component--->  const [newbalance] =
    useContractCall({
      abi: tokenFarmInterface,
      address: tokenFarmAddress,
      method: "newbalance",
      args: [],
    }) ?? []

    return newbalance

However it still returns undefined which is odd. The same call works for example when i return directly via the smart contract.
