### ISSUE TITLE
Update Ethers to >= 5.5.0

### ISSUE THREAD

**Issue by wschwab** [EthWorks/useDApp#379]
Hi!

I was hoping you'd be able to bump Ethers to at least 5.5.0 so we can get all the wonderful goodness there, like better overloaded function resolution ([source](https://github.com/ethers-io/ethers.js/issues/1432#issuecomment-947217835)) and one-line avatar resolution ([source](https://twitter.com/wslyvh/status/1453374523382845447)).

Thanks!

**Comment by JayWelsh** [comment]
This is important to avoid an issue such as this when using TypeScript:

![Screenshot 2021-11-06 at 02 59 20](https://user-images.githubusercontent.com/14224459/140592534-ba2ed353-16f9-4123-a877-1294cc59807f.png)

**Comment by JayWelsh** [comment]
This is important to avoid issues such as this when using TypeScript:

![Screenshot 2021-11-06 at 02 59 20](https://user-images.githubusercontent.com/14224459/140592625-a1af454c-ee12-4cae-9d34-4f07af67f83e.png)

**Comment by jacobedawson** [comment]
Looking forward to see this pull request merged
