### ISSUE TITLE
Notification documentation mentions different unknown entities

### ISSUE THREAD

**Issue by ccarnino** [EthWorks/useDApp#389]
The [Notification documentation](https://usedapp.readthedocs.io/en/latest/guide.html?highlight=notificationContent#notifications) mentions different entities that as a reader I don't know where they come from.

Where do I get `NotificationElement`? `import { useNotifications, NotificationElement } from '@usedapp/core'`?

But most importantly, in the example snippet the `notificatioContent` variable is used, but I have no idea where it comes from:
```
{notifications.map((notification) => {
  if ('transaction' in notification)
    return (
      <NotificationElement
        key={notification.id}
        icon={notificationContent[notification.type].icon}
        title={notificationContent[notification.type].title}
        transaction={notification.transaction}
        date={Date.now()}
      />
    )
  else
    return (
      <NotificationElement
        key={notification.id}
        icon={notificationContent[notification.type].icon}
        title={notificationContent[notification.type].title}
        date={Date.now()}
      />
    )
})}

Can you help me? 
After I can make a PR updating the documentation website.
Thanks

**Comment by nezouse** [comment]
Hi, sorry for the confusion, example used here is surely not the best without context.

`NotificationElement` is a custom react component to display the notification and notificationContent is an object with additional data for it based on the type of the notification.

Here is the whole file from where this code was taken: https://github.com/EthWorks/useDApp/blob/master/packages/example/src/components/Transactions/History.tsx#L154

**Comment by nezouse** [comment]
That's right, the only part of @usedapp/core package is the `useNotifications` hook

**Comment by ccarnino** [comment]
Perfect, thanks for the confirmation!
