### ISSUE TITLE
Remove web3-react dependency

### ISSUE THREAD

**Issue by tt-marek** [EthWorks/useDApp#409]
It feels like it is time to remove web3-react and create own state machine to manage connection state.

### Motivation
1. Unwanted warnings (see #342)
2. web3-react connectors add complexity are mostly unused, make it difficult to integrate with [web3modal](https://github.com/Web3Modal/web3modal) 
(related #345, #332, #282, #292)
3. Lack of support for multiple networks connections (related #132)
4. Poor error management (see [doc](https://usedapp.readthedocs.io/en/latest/guide.html#handling-wallet-activation-errrors), #337)
5. Challenges in getting issues resolved/PRs merged

### Implementation proposal

Only one (or zero) network can be active for writing while multiple networks can be active for reading. 
Use `activate(provider)` to switch active networks.

#### Configuration

New configuration format:

```ts
const config: Config = {
    writeNetworks: [Mainnet],
    readNetworks: [{
      network: Mainnet,
      url: 'https://mainnet.infura.io/v3/62687d1a985d4508b2b7a24827551934',
      provider: [],
      default: true
    }]
}
```

#### Error handling

```ts
const {errors} = useEthers();
```

Returns an array of typed errors `ConnectionError[]`, related to connection.

Errors will disappear once the reason is not valid anymore (e.g. activation failed is cleared by the next successful activations)

**Comment by jhirn** [comment]
I'd be all for this as web3-react seems to not be updated very frequently and troubleshooting issues with useDapp is quite an exercise on determining if the problem is here, there, or all the way in ethers. 

useDapp has been an amazing library. I thank you for your efforts on it.

**Comment by gsteenkamp89** [comment]
Yeah web3-react seems to not be actively maintained. The Ledger connector is using deprecated U2F browser API, so direct Ledger support is currently not possible with useDapp while web3-react is a dependency. This kind of issue is likely to get worse and worse very quickly as that repo becomes stale..

**Comment by JayWelsh** [comment]
I think this issue can be closed now 🌈
