### ISSUE TITLE
Adding Optimism and Optimism Kovan Testnet to UseDApp.  Greatly Needed

### ISSUE THREAD

**Issue by CrazyCaptian** [EthWorks/useDApp#444]
I cant find a way to port my react app to Optimism Kovan Testnet.  Everytime it says Unsupported Token
Mumbai and Kovan work fine

**Comment by ccarnino** [comment]
They have been added 🙌. Probably this issue can be closed now.

**Comment by CrazyCaptian** [comment]
TY
