### ISSUE TITLE
Is there a way to force a refresh of multicalls before the next blocknumber?

### ISSUE THREAD

**Issue by DoubleOTheven** [EthWorks/useDApp#463]
I would like to update the view immediately upon a successful transaction, but currently all `useContractCalls` hooks only update on the next block. 

1. Is there a way to refresh immediately?
2.  If not, would something like this work?

```js
const multicallData = useContractCalls(...)

const { forceRefresh } = useChainStateContext()  // Need to add this callback to the useDApp API. Could be as simple as an incrementer that forces useEffect to refire (aka the multicall)

const handleSubmit = async () => {
  const tx = await treasury.release(account)
  await tx.wait(1).then(() => forceRefresh())
}
```

**Comment by wminshew** [comment]
have you tested whether this is an issue on mainnet or a testnet or if it's just a local thing? for awhile I was manually emitting events after successful transactions (and had some event listener logic to de-dupe events) which worked really well on the local (hardhat) network, but didn't seem to add any value once we moved testing to ropsten

**Comment by DoubleOTheven** [comment]
I am running this on the local network. The success message returns before the next block, but I still have to wait for the next block number for an update on screen when using `useContractCalls`

**Comment by DoubleOTheven** [comment]
nm. Found a way to use the library as it was intended...

**Comment by wminshew** [comment]
@DoubleOTheven would you mind leaving some notes about your solution for future issue-viewers who might be looking for options to do something similar?

**Comment by D-Ig** [comment]
> nm. Found a way to use the library as it was intended...

@DoubleOTheven same, I'd be happy if you could share some details what was the workaround
