### ISSUE TITLE
Replace enum ChainId with a set of constants. Replace ChainId with number

### ISSUE THREAD

**Issue by sz-piotr** [EthWorks/useDApp#47]
Using ChainId limits the possibilities of the users to interact with other chains. If I had a chain with id 777 I wouldn't be able to use the library.

**Comment by marekkirejczyk** [comment]
btw list of chains, we could use to have a comprehensive support

https://chainid.network/chains.json

**Comment by tarrencev** [comment]
In line with this suggestion, we should consider using chain agnostic identifiers following [CAIP standards](https://github.com/ChainAgnostic/CAIPs). These seem to be the standards with the most momentum behind them (wallet connect/metamask).

**Comment by Benek7831** [comment]
Hi guys, 

As I understand, it is still not possible to use useDapp with chains other than the ones available through _ChainId_ ?
So fantom is available but not the testnet, and avalanche too, right ?

**Comment by tt-marek** [comment]
Continued in #408
