### ISSUE TITLE
Error when trying to activate walletconnect with web3-react connector

### ISSUE THREAD

**Issue by ryanchanplc** [EthWorks/useDApp#519]
Hi guys ,

I followed the example and tried to activate web3-react walletconnect connector but i am facing an error below

`walletconnect-connector.esm.js:238 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'connected')`

currently i am using usedApp @ v0.10.1 with web3-react/walletconnect-connector @v.6.2.10 while the example is 0.10.0 and 6.2.4

Any idea? Thanks

**Comment by FanManutd** [comment]
Same problem

**Comment by quagliero** [comment]
Also same problem. Wonder if this is anything to do with removing web3-react as a dependency? 🤷🏻‍♂️

**Comment by vm06007** [comment]
can someone drop me original example to try?

**Comment by LongTran12** [comment]
you can try walletconnect version:    "@web3-react/walletconnect-connector": "^7.0.2-alpha.0",

**Comment by ryanchanplc** [comment]
i confirm it is `@web3-react/walletconnect-connector` version problem as @quagliero mention any version after 6.2.8 will not work.
