### ISSUE TITLE
how to send ERC20 token?

### ISSUE THREAD

**Issue by ykf2020** [EthWorks/useDApp#548]
Hi all,
I am trying to send ERC20 tokens with useDapp. However, the document about sendTransaction is all about how to send ETH.
What's is the configuration I can set to send custom ERC20 tokens with useDapp?

**Comment by ilyxium** [comment]
did you figure this out

**Comment by nezouse** [comment]
Hey, you just need to use the `transfer` function on ERC20 token.
```js
const {state, send} = useContractFunction(contract, 'transfer');
send(address, amount);
```

**Comment by ykf2020** [comment]
@ilyxium @nezouse 
thank u a lot, I figure it out after reading EIP20 standard
