### ISSUE TITLE
is there a way to sign a message?

### ISSUE THREAD

**Issue by patcito** [EthWorks/useDApp#91]
Thinking of something like this?

https://github.com/NoahZinsmeister/web3-react/blob/3a4fbf5d6a22b24df901c6d8eda0cc23b15d8916/example/pages/index.tsx#L352

Or do I need to do it manually?

Thanks.

**Comment by marekkirejczyk** [comment]
@patcito It is the right way to do it.

```ts
  const {library} = useEthers()
  ...
  library
    .getSigner(account)
    .signMessage('👋')
  ...
```

Is see no advantage in building abstraction on the top of that.
