### ISSUE TITLE
Troubles connecting to local Ganache

### ISSUE THREAD

**Issue by Sagato** [EthWorks/useDApp#96]
Hello,

first of all, thank you for the amazing work!

I am using a truffle Project to deploy my migrations to a local ganache instance.
Isn't it possible to connect useDapp to my ganache local network running on localhost:7545?

Regards

**Comment by marekkirejczyk** [comment]
It is a bit tricky, but you can do it
- you need to setup your Ganache to have existing chainId
- deploy multicall and set the address in config
- configure MetaMask to use ganache

It is on the roadmap, but a bit further ahead (in configuration milestone)

Will accept PR. :)

**Comment by marekkirejczyk** [comment]
with version 0.3.3 you should be able to connect with MetamMask as long as chainId is 1337

**Comment by Sagato** [comment]
Hey mate. Awesome thank you, I will try it out! I was using useWallet for the connections but will now definetly switch to useDApp. I guess there are some more features to come? Please stay as lean as possible, I would prefer having less functions working properly over massive features :).

**Comment by Sagato** [comment]
I am currrently seeing this issue after the newest update: provider.js?28e5:30 Missing multicall address for chain id 1337

**Comment by JackDiSalvatore** [comment]
> with version 0.3.3 you should be able to connect with MetamMask as long as chainId is 1337

Version 0.3.3 ?  I see the latest version as 0.3.15. Is version 0.3.3 available via npm/yarn yet?

**Comment by nezouse** [comment]
There was a lot of small releases, but if you update to 0.3.15 it will have changes from 0.3.3 as well.
But if you really want to install some specific version you can always do `yarn add @usedapp/core@0.3.3`.

**Comment by jacobedawson** [comment]
Hi - useDapp looks really cool and very easy to get started with, but I am also seeing the error "Missing multicall address for chain id 1337". 

I am using @usedapp/core 0.3.15, my local network is http://127.0.0.1:8545 (with the local network provided by Hardhat, chainId 1337).

Having some documentation around connecting to localhost will be really helpful, I imagine most devs will be testing locally before using e.g. Infura.

Thanks!

**Comment by tt-marek** [comment]
Implemented in #245
